### ISSUE TITLE
cannot import name 'UTC' from 'datetime' (/usr/lib/python3.10/datetime.py)

### ISSUE THREAD

**Issue by Orgoth** [WinChua/pyinnodb#50]
Traceback (most recent call last):
  File "/usr/lib/python3.10/runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/usr/lib/python3.10/runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "/home/isley/tmp/lenny/./pyinnodb.sh/__main__.py", line 2, in <module>
  File "/home/isley/tmp/lenny/./pyinnodb.sh/pyinnodb/cli/__init__.py", line 2, in <module>
  File "/home/isley/tmp/lenny/./pyinnodb.sh/pyinnodb/cli/iter_record.py", line 7, in <module>
  File "/home/isley/tmp/lenny/./pyinnodb.sh/pyinnodb/sdi/table.py", line 21, in <module>
  File "/home/isley/tmp/lenny/./pyinnodb.sh/pyinnodb/disk_struct/data.py", line 2, in <module>
ImportError: cannot import name 'UTC' from 'datetime' (/usr/lib/python3.10/datetime.py)

**Comment by Orgoth** [comment]
> thanks for your feedback, it's fix now. can you download the latest version of pyinnodb.sh and try again @Orgoth

@WinChua Thank you very much, it is working now.

Have a nice day.
